#ifndef CGAL_SHAPE_DETECTION_REGION_GROWING_ON_FACE_GRAPH_H
#define CGAL_SHAPE_DETECTION_REGION_GROWING_ON_FACE_GRAPH_H

#include <CGAL/Shape_detection/Region_growing/Region_growing_on_face_graph/Propagation_conditions_on_face_graph.h>
#include <CGAL/Shape_detection/Region_growing/Region_growing_on_face_graph/Connectivity_on_face_graph.h>

#endif // CGAL_SHAPE_DETECTION_REGION_GROWING_ON_FACE_GRAPH_H
